-- ====================================================================
-- KőszegPass – Supabase tábla definíciók
-- Futtasd le a Supabase SQL Editor-ban
-- ====================================================================

-- 1. koszeg_passes – a pass rekordok (egy sor = egy vásárolt pass)
CREATE TABLE IF NOT EXISTS koszeg_passes (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    serial              BIGINT GENERATED BY DEFAULT AS IDENTITY,  -- kiadási sorszám (auto, sorfolytonos) → statisztika
    holder_name         TEXT NOT NULL,
    holder_email        TEXT NOT NULL,
    pass_type           TEXT NOT NULL CHECK (pass_type IN ('individual', 'family')),
    status              TEXT NOT NULL DEFAULT 'active'
                            CHECK (status IN ('pending', 'active', 'expired', 'cancelled')),
    qr_token            TEXT UNIQUE NOT NULL DEFAULT gen_random_uuid()::text,
    stripe_session_id   TEXT UNIQUE,
    amount_paid         INTEGER,    -- fillérben (HUF × 100, Stripe formátum)
    purchased_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ NOT NULL,
    hotel_source        TEXT,       -- melyik szállodából szkennelte a regisztráló QR-t
    origin_zip          TEXT,       -- honnan érkezett a turista (ir. szám)
    phone               TEXT,
    extra_info          TEXT,       -- egyéb turisztikai statisztikai adat
    billing_zip         TEXT,
    billing_city        TEXT,
    billing_address     TEXT,
    billingo_invoice_id TEXT,
    slug                TEXT UNIQUE,
    created_at          TIMESTAMPTZ DEFAULT now()
);

-- Index az egyszerűsített URL alapú kereséshez
CREATE INDEX IF NOT EXISTS idx_koszeg_passes_slug
    ON koszeg_passes (slug);

-- Index az email alapú kereséshez (wallet újra letöltés stb.)
CREATE INDEX IF NOT EXISTS idx_koszeg_passes_email
    ON koszeg_passes (holder_email);

-- Index a QR token kereséshez (validáció – ez a leggyakoribb query)
CREATE INDEX IF NOT EXISTS idx_koszeg_passes_qr_token
    ON koszeg_passes (qr_token);

-- Index a stripe session idempotencia ellenőrzéshez
CREATE INDEX IF NOT EXISTS idx_koszeg_passes_stripe_session
    ON koszeg_passes (stripe_session_id);

-- --------------------------------------------------------------------
-- MIGRÁCIÓ: sorszám hozzáadása MÁR LÉTEZŐ táblához
-- (friss telepítésnél a fenti CREATE TABLE már tartalmazza; ez idempotens)
-- A meglévő sorok visszamenőleg is kapnak sorszámot.
ALTER TABLE koszeg_passes
    ADD COLUMN IF NOT EXISTS serial BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Egyediség + gyors "hányadik pass" statisztika
CREATE UNIQUE INDEX IF NOT EXISTS idx_koszeg_passes_serial
    ON koszeg_passes (serial);

-- ====================================================================
-- 2. pass_scans – partner scan statisztika (opcionális, csak ha QR-t olvasnak)
CREATE TABLE IF NOT EXISTS pass_scans (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pass_id     UUID NOT NULL REFERENCES koszeg_passes(id) ON DELETE CASCADE,
    partner_id  TEXT,           -- a partner azonosítója (pl. 'rajnis-etterem')
    scanned_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index a pass_id alapú statisztika lekérdezéshez
CREATE INDEX IF NOT EXISTS idx_pass_scans_pass_id
    ON pass_scans (pass_id);

-- Index a partner statisztikához
CREATE INDEX IF NOT EXISTS idx_pass_scans_partner_id
    ON pass_scans (partner_id);

-- ====================================================================
-- 3. Row Level Security (RLS)
-- A backend service role keyvel dolgozik → bypass RLS
-- A frontend anonimous keyvel → korlátozott hozzáférés

ALTER TABLE koszeg_passes ENABLE ROW LEVEL SECURITY;
ALTER TABLE pass_scans    ENABLE ROW LEVEL SECURITY;

-- Service role: full access (backend functions)
-- (A service role automatikusan bypass-olja az RLS-t)

-- ⚠️  RÉGI, HIBÁS POLICY ELTÁVOLÍTÁSA:
--     az USING(true) az anon kulcsnak az ÖSSZES sort és ÖSSZES oszlopot kiadta
--     (email, telefon, cím, qr_token) → PII- és token-szivárgás. Töröljük.
DROP POLICY IF EXISTS "validate_by_token" ON koszeg_passes;

-- Nincs publikus SELECT policy → az anon kulcs KÖZVETLENÜL nem olvassa a táblát.
-- A publikus oldalak a lenti security definer függvényeken keresztül férnek hozzá,
-- amelyek CSAK a megjelenítéshez szükséges, nem érzékeny mezőket adják vissza.

-- pass_scans: csak a service role írhat
DROP POLICY IF EXISTS "service_only_scans" ON pass_scans;
CREATE POLICY "service_only_scans" ON pass_scans
    FOR ALL
    USING (false); -- csak service role (RLS bypass) írhat

-- ====================================================================
-- 4. Publikus, TOKEN-ALAPÚ hozzáférés (Fázis 3 – biztonságos megjelenítés)
--    A slug önmagában NEM ad hozzáférést – kell a qr_token (nem kitalálható).
-- ====================================================================

-- 4/a) Pass a QR-token alapján – a /p/:slug?token=... oldalhoz.
--      Nem ad vissza email/telefon/cím/stripe adatot.
CREATE OR REPLACE FUNCTION public.get_koszeg_pass_by_token(p_token TEXT)
RETURNS TABLE (
    id           UUID,
    serial       BIGINT,
    holder_name  TEXT,
    pass_type    TEXT,
    status       TEXT,
    purchased_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    slug         TEXT
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT id, serial, holder_name, pass_type, status, purchased_at, expires_at, slug
    FROM koszeg_passes
    WHERE qr_token = p_token
    LIMIT 1;
$$;

-- 4/b) Pass a Stripe session alapján – a vásárlás utáni /pass/success oldalhoz.
--      A vevő épp fizetett → megkapja a qr_token-t is (QR + állandó link generálásához).
CREATE OR REPLACE FUNCTION public.get_koszeg_pass_by_session(p_session TEXT)
RETURNS TABLE (
    id           UUID,
    serial       BIGINT,
    holder_name  TEXT,
    pass_type    TEXT,
    status       TEXT,
    purchased_at TIMESTAMPTZ,
    expires_at   TIMESTAMPTZ,
    slug         TEXT,
    qr_token     TEXT
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT id, serial, holder_name, pass_type, status, purchased_at, expires_at, slug, qr_token
    FROM koszeg_passes
    WHERE stripe_session_id = p_session
    LIMIT 1;
$$;

-- Csak az anon/authenticated szerep futtathatja (a public alap-EXECUTE visszavonva)
REVOKE ALL ON FUNCTION public.get_koszeg_pass_by_token(TEXT)   FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_koszeg_pass_by_session(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_koszeg_pass_by_token(TEXT)   TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_koszeg_pass_by_session(TEXT) TO anon, authenticated;
-- ====================================================================
